[workspace]
members = [
  "program",
  "lib/fetch",
  "lib/ethereum-trie",
  "lib/basics",
  "script",
  "server",
]

[patch.crates-io]
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
