[workspace]
[package]
version = "0.1.0"
name = "sp1-safe-script"
edition = "2021"

[dependencies]
const-hex = "1.11.1"
sp1-core = { git = "https://github.com/succinctlabs/sp1.git", tag = "v0.0.2" }
sp1-safe-basics = { path = "../lib/basics" }
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", tag = "v0.0.2" }