[workspace]
[package]
version = "0.1.0"
name = "sp1-safe-verifier"
edition = "2021"

[[bin]]
name = "sp1-safe-verifier-generator"
path = "src/main.rs"

[dependencies]
const-hex = "1.11.1"
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.4-testnet", features = ["plonk"] }
