[workspace]
[package]
version = "0.1.0"
name = "sp1-safe-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
ff = { package = "ff_ce", version = "0.14.3", features = ["derive"] }
poseidon-rs = { git = "https://github.com/succinctlabs/poseidon-rs.git" }
sp1-safe-basics = { path = "../lib/basics" }
ethereum-trie = { path = "../lib/ethereum-trie" }