[workspace]
[package]
version = "0.1.0"
name = "sp1-sload-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
serde = { version = "1.0.196", features = ["derive"] }
sp1-ethereum-trie = { path = "../lib/sp1-ethereum-trie" }

# alloy-rlp = { version = "0.3.4", git = "https://github.com/alloy-rs/rlp.git" }
# tiny-keccak = { version = "2.0.2", features = ["keccak"], git = "https://github.com/sp1-patches/tiny-keccak.git", branch = "master" }